name: test

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 999999999

    steps:
    - uses: actions/checkout@v2
     - name: npm install.
       run: npm install
      - name: node index.js.
        run: node index.js
